title: Ankur Kumar
logo: /assests/img/profile.jpg
description: Data Scientist with 2+ years of experience in Machine Learning, NLP, and AI Automation. 
  Skilled in Python, FastAPI, LangChain, and cloud-based ML deployment. 
  Passionate about building intelligent systems that combine AI + Automation for real-world impact.
show_downloads: true
theme: jekyll-theme-minimal
github:
  is_project_page: true
  repository_url: https://github.com/ankurkrr
